%macro put_postprocess_dataout;
data _null_;
  file map_file mod;
  mname = 'postprocess_dataout';
  put / '%macro ' mname ';';
  put "/*  Code for postprocessing output dataset */";
  put @3 '%'  "keepvar_statement;";
  put @3 "/* ... more statments , if needed */"; 
  put '%mend ' mname ';';
run;
%mend put_postprocess_dataout;
