%macro put_preprocess_datain(dtin_no, dtin_nm);
data _null_;
  file map_file mod;
  mname = 'preprocess_datain' || strip(put(&dtin_no, 3.));
  put / '%macro ' mname ';';
  put "/*  Code for preprocessing `&dtin_nm` dataset */";
  put @3 '%*'  "_datain_varsinit&dtin_no;";
  put @3 "/* ... more statments , if needed */"; 
  put '%mend ' mname ';';
%mend put_preprocess_datain;
