%macro zzz_05main_execute;

%put ====> Macro `zzz_05main_execute` starts here;
%global HRS_RAND2LONG_version traceit vars_map;
%global waves_list waves_elist waves_sel wave_max_no;

%_usetup_mvars;

%let DATAIN_NAME =&datain;
%global map_file waves_sel  waves_sel2;
%**global xlsx_fnm map_info;
%global aux_outpath;

%let waves_sel = %upcase(&waves_sel);
%put wave_sel := &waves_sel;
%let  waves_sel2 = %sysfunc(tranwrd(%quote(&waves_sel) ,TO, :));
%put wave_sel2 := &waves_sel2;

data _MAP2Long;
 set &map_info;
run;

 ods listing close;
 
 proc template;
  define style styles.custom;
    parent=styles.HTMLBlue;
    class ContentTitle /
      just=center
      font_weight=bold
      font_size=10pt
      color=black
      background=white
      textdecoration=underline
      pretext="<h1>Table &tbl</h1>";
  end;
run; 

 ods html  path      = "&prj_path\&dir_name\&aux_out" (URL=NONE)
           file      = "05-traceit-body.html"
           contents  = "05-traceit-contents.html"
           frame     = "05-traceit-frame.html"
           style     = styles.custom
 ;
 
%*traceit(_MAP2Long);

%** html_aux_report;

/* --- Dataset `dictionary_init` created */
%create_dictionary_init; 

/*---  Create `dictionary_template` dataset ---*/


%dictionary_template;

/* --- Dataset `vars_map_init` created from _MAP2Long*/
%if (&vars_map = Y or &vars_map = E) %then %create_vars_map_init;

/*---  Create `dictionary_template` dataset with 0 rows ---*/
%dictionary_template;

/*--- Create `vars_map_template` dataset  and `waves_elist` macro variables */
%if (&vars_map = Y or &vars_map = E ) %then %vars_map_template;

/*--- Create `_dictionary` dataset */
%create_dictionary;

%_YE_block;
 

ods html close;
ods listing;

%put :::;
%let n_vout = %attrn_nlobs(_dictionary);

/* --- Map file initiated ---*/
data _null_;
  file map_file;
  put "/* This is map_file `&tbl._map_file.inc` for `&tbl._table` dataset */";
  put "/* Repo name := &repo_name (version &repo_version) */";
  put "/* Project name := &prj_name */";
  put "/* Excel map: &xlsx_name..xlsx */";
  put "/* Date stamp: &sysdate  */";
  put /;
run;

%macro needs_work;
data _null_;
  file map_file;
  *length map_info $ 200;
  length waves_list $200;
  length map_file $200;
  *map_info = symget('map_info');
  waves_list = symget('waves_list');
  map_file = symget('map_file');
  
  put / "/*========================";
  put "File name: " map_file;
  put "   File was generated by script:";
  put "     `05-create-macros.sas`. Version: &HRS_RAND2LONG_version";
  put "      executed on &sysdate..";
   *put "   Excel spreadsheet with map info:"  @40 map_info;
  put "   Waves list: " waves_list;

  *** put / "MAP_INFO dataset(input): `&vars_map`";
  put / " List of macros defined in this file: ";
  put;
  put "  - clength_statements (invoked by `create_template_longout` macro)";
  put "  - label_statements   (invoked by `create_template_longout` macro)";
  put "  - format_statements  (invoked by `create_template_longout` macro)";
  put "  - create_template_longout (creates data template)";
  put;  
  put "  - _datain_varsinit1 (invoked by `preprocess_wave` macro)";
  put "  - preprocess_wave (invoked by _hrs_wave[#] macros)";
  put "  - postprocess_wave (invoked by _hrs_wave[#] macros.  if INW =1 then output)";
  put "  - _hrs_wave[#] macros (invoked by `process_selected_waves` macro)";
  put;  
  put "  - preprocess_datain1 (place holder, invoked by `create_outdata(datain)`)";
  put "  - process_selected_waves (invoked by `create_outdata`)";
  put "  - keepvar_statement (invoked by `postprocess_dataout` macro)"; 
  put "  - postprocess_dataout (invoked by `create_outdata`)";
  put "  - create_outdata macro defined elsewhere";
  put "===========================*/" /;
run;
%mend needs_work;

/* ===> Macro`put_init_macro_stmnts`
 appends definitions of macros listed below  to `map_file`: 
 * `label_statements`
 * `clength_statements`  
 * `format_statement
 * `create_template_longout`
 * `keepvar_list`
*/
%put_init_macro_stmnts;


%put --- vars_map := &vars_map;
%if (&vars_map = Y or &vars_map =E) %then %do;
  %put_mrg2_stmnts; /* set mrg2 */


filename map_file clear;
%end; /*if */
%put Macro `zzz_05main_execute` ends here;

%mend zzz_05main_execute;